name: image_hash
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: Matthew <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  image: ^1.1.26
  args: any

dev_dependencies:
  test: ^0.12.0
executables:
  image-compare: compare
